import { describe, expect, it } from 'vitest';
import { generateDispatchShims_ } from '../../codegen/generate-shims.js';

describe('generateDispatchShims_', () => {
  it('emits one static dispatch function per route name, forwarding to __rbacDispatch', () => {
    const output = generateDispatchShims_(['getBillingReport', 'getSubmissionMeta'], {
      packageName: '@evinle/gas-rbac',
    });

    expect(output).toContain(
      'export function getBillingReport(...args: unknown[]) { return __rbacDispatch("getBillingReport", ...args); }',
    );
    expect(output).toContain(
      'export function getSubmissionMeta(...args: unknown[]) { return __rbacDispatch("getSubmissionMeta", ...args); }',
    );
  });

  it('prefixes the output with an auto-generated header and the __rbacDispatch import', () => {
    const output = generateDispatchShims_(['ping'], { packageName: '@evinle/gas-rbac' });
    const lines = output.split('\n');

    expect(lines[0]).toBe('// AUTO-GENERATED by gas-rbac codegen -- do not edit by hand.');
    expect(lines[1]).toBe("import { __rbacDispatch } from '@evinle/gas-rbac';");
  });

  it('imports __rbacDispatch from a caller-supplied package name instead of a hardcoded one', () => {
    const output = generateDispatchShims_(['ping'], { packageName: '@acme/internal-gas-rbac' });
    expect(output.split('\n')[1]).toBe("import { __rbacDispatch } from '@acme/internal-gas-rbac';");
  });
});
