export interface GenerateDispatchShimsOptions {
  // No default -- the published package name is a hosting decision (npm,
  // an internal registry, a workspace path), not something this pure
  // module should assume on a caller's behalf.
  packageName: string;
}

export function generateDispatchShims_(routes: readonly string[], options: GenerateDispatchShimsOptions): string {
  const { packageName } = options;
  const header = [
    '// AUTO-GENERATED by gas-rbac codegen -- do not edit by hand.',
    `import { __rbacDispatch } from '${packageName}';`,
  ];
  const shims = routes.map(
    (name) =>
      `export function ${name}(...args: unknown[]) { return __rbacDispatch(${JSON.stringify(name)}, ...args); }`,
  );
  return [...header, ...shims].join('\n');
}
